In [4]:
import torch

In [5]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [6]:
x.requires_grad = True
x.grad

In [7]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad == 4 * x

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y = x.sum()
print(y)
y.backward()
x.grad

tensor(6., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1.])

In [11]:
x.grad.zero_()
y =  x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [12]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [13]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [16]:
a =  torch.randn(size = (), requires_grad = True)
b = f(a)
b.backward()
a.grad == b / a

tensor(True)