In [34]:
import torch

In [35]:
x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [36]:
#Guesing this gives us the size of the tensor
x.numel()

12

In [37]:
#We are checking the tensor shape in this case we have a 1D tensor so it's shape ==  it's size
x.shape

torch.Size([12])

In [38]:
x.reshape(3, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [40]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [41]:
torch.rand(1, 20)

tensor([[0.0307, 0.0997, 0.6365, 0.1833, 0.3798, 0.8026, 0.4395, 0.5843, 0.8691,
         0.4542, 0.4998, 0.7422, 0.4368, 0.5482, 0.4857, 0.6848, 0.8235, 0.4098,
         0.4308, 0.6359]])

In [42]:
torch.tensor([[1, 3, 4], [2, 5, 6], [12, 52, 52]])

tensor([[ 1,  3,  4],
        [ 2,  5,  6],
        [12, 52, 52]])

In [48]:
x = x.reshape(3, 4)

In [49]:
x[-1], x[1 : 3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [51]:
x[1, 2] = 17
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [52]:
x[:2, : ] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [53]:
torch.exp(x)

tensor([[162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [162754.7969, 162754.7969, 162754.7969, 162754.7969],
        [  2980.9580,   8103.0840,  22026.4648,  59874.1406]])

In [54]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
y = torch.tensor([1, 2, 3, 4, 5, 6])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 2,  4,  6,  8, 10, 12]),
 tensor([0, 0, 0, 0, 0, 0]),
 tensor([ 1,  4,  9, 16, 25, 36]),
 tensor([1., 1., 1., 1., 1., 1.]),
 tensor([    1,     4,    27,   256,  3125, 46656]))

In [57]:
x = torch.arange(12,  dtype = torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2 ,1]])
x, y
#axis zero is rows and axis one is cols
torch.cat((x, y), dim = 0), torch.cat((x, y), dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [58]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [59]:
x.sum()

tensor(66.)

In [60]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [61]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [63]:
before = id(y)
y = x + y
id(y) == before

False

In [64]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2158920747824
id(z): 2158920747824


In [65]:
a = x.numpy()
b = torch.from_numpy(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

In [67]:
a = torch.tensor([3.5])
a, a.item, float(a), int(a)

(tensor([3.5000]), <function Tensor.item>, 3.5, 3)