In [2]:
import torch

In [3]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [4]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [5]:
x[2]

tensor(2)

In [8]:
len(x)

3

In [10]:
x.shape

torch.Size([3])

In [13]:
a = torch.arange(6).reshape(3, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [14]:
a.T        

tensor([[0, 2, 4],
        [1, 3, 5]])

In [21]:
a = torch.zeros(3, 3)
a = torch.tensor([[1, 2, 3], [2, 0 , 4], [3, 4, 0]])
a == a.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [22]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [25]:
a = torch.arange(6, dtype = torch.float32).reshape(2, 3)
b = a.clone()
a, a + b

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [26]:
a * b

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [28]:
a = 2
x = torch.arange(24).reshape(2, 3, 4)
a + x, (a * x).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [30]:
x = torch.arange(3, dtype= torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))