In [3]:
import torch

In [4]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [5]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
x[2]

tensor(2)

In [7]:
len(x)

3

In [8]:
x.shape

torch.Size([3])

In [9]:
a = torch.arange(6).reshape(3, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
a.T        

tensor([[0, 2, 4],
        [1, 3, 5]])

In [11]:
a = torch.zeros(3, 3)
a = torch.tensor([[1, 2, 3], [2, 0 , 4], [3, 4, 0]])
a == a.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [12]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
a = torch.arange(6, dtype = torch.float32).reshape(2, 3)
b = a.clone()
a, a + b

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [14]:
a * b

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [15]:
a = 2
x = torch.arange(24).reshape(2, 3, 4)
a + x, (a * x).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [60]:
x = torch.arange(3, dtype = torch.float32)
x, x.sum()
a = torch.arange(18, dtype = torch.float32)

In [61]:
a.shape, a.sum()

(torch.Size([18]), tensor(153.))

In [62]:
a.sum(axis = 0)

tensor(153.)

In [63]:
a.shape, a.sum(axis = -1).shape

(torch.Size([18]), torch.Size([]))

In [64]:
a.sum(axis = [0, 1]) == a.sum()

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [65]:
a.mean(), a.sum() / a.numel()

(tensor(8.5000), tensor(8.5000))

In [66]:
a.mean(axis = 0), a.sum(axis = 0) / a.shape[0]

(tensor(8.5000), tensor(8.5000))