In [3]:
import torch

In [4]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [5]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
x[2]

tensor(2)

In [7]:
len(x)

3

In [8]:
x.shape

torch.Size([3])

In [9]:
a = torch.arange(6).reshape(3, 2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
a.T        

tensor([[0, 2, 4],
        [1, 3, 5]])

In [11]:
a = torch.zeros(3, 3)
a = torch.tensor([[1, 2, 3], [2, 0 , 4], [3, 4, 0]])
a == a.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [12]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
a = torch.arange(6, dtype = torch.float32).reshape(2, 3)
b = a.clone()
a, a + b

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [14]:
a * b

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [15]:
a = 2
x = torch.arange(24).reshape(2, 3, 4)
a + x, (a * x).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [70]:
x = torch.arange(3, dtype = torch.float32)
x, x.sum()
a = torch.arange(6, dtype = torch.float32).reshape(2, 3)

In [71]:
a.shape, a.sum()

(torch.Size([2, 3]), tensor(15.))

In [72]:
a.sum(axis = 0)

tensor([3., 5., 7.])

In [73]:
a.shape, a.sum(axis = 1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [74]:
a.sum(axis = [0, 1]) == a.sum()

tensor(True)

In [75]:
a.mean(), a.sum() / a.numel()

(tensor(2.5000), tensor(2.5000))

In [76]:
a.mean(axis = 0), a.sum(axis = 0) / a.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [82]:
print("A is", a)
sum_a = a.sum(axis = 1, keepdims = True)
sum_a, sum_a.shape

A is tensor([[0., 1., 2.],
        [3., 4., 5.]])


(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [83]:
a / sum_a

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [84]:
a.cumsum(axis = 0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [86]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [87]:
torch.sum(x * y)

tensor(3.)

In [92]:
a.shape, x.shape, torch.mv(a, x), a@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [91]:
b = torch.ones(3, 4)
torch.mm(a, b), a@b

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

In [96]:
u = torch.tensor([3., -4.])
torch.norm(u)

tensor(5.)

In [97]:
torch.abs(u).sum()

tensor(7.)

In [98]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [103]:
x = torch.arange(24).reshape((2, 3, 4))
x, len(x)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 2)